# ! /usr/bin/env python3
# -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5
# in conjunction with Tcl version 8.6
# Nov 28, 2022 08:58:18 AM EST  platform: Windows NT

import sys
import tkinter as tk
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)
import SwipeDown_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40'  # X11 color: #666666
_ana1color = '#c3c3c3'  # Closest X11 color: 'gray76'
_ana2color = 'beige'  # X11 color: #f5f5dc
_tabfg1 = 'black'
_tabfg2 = 'black'
_tabbg1 = 'grey75'
_tabbg2 = 'grey89'
_bgmode = 'light'


class SwipeDown:
    def __init__(self, top):
        """This class configures and populates the toplevel window.
            top is the toplevel containing window."""
        self.top = top
        top.geometry("600x450+562+124")
        top.minsize(120, 1)
        top.maxsize(4924, 1901)
        top.resizable(1, 1)
        top.title("Toplevel 0")
        top.configure(background="#400080")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#400080")

        self.Labelframe1 = tk.LabelFrame(self.top)
        self.Labelframe1.place(relx=0.017, rely=0.044, relheight=0.944, relwidth=0.967)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="#000000")
        self.Labelframe1.configure(text='''SwipeDown''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Label1 = tk.Label(self.Labelframe1)
        self.Label1.place(relx=0.017, rely=0.071, height=21, width=543, bordermode='ignore')
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''SwipeDown options:''')
        self.Label2 = tk.Label(self.Labelframe1)
        self.Label2.place(relx=0.017, rely=0.141, height=21, width=76, bordermode='ignore')
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Web Scrape''')
        self.scrapeButton = tk.Button(self.Labelframe1)
        self.scrapeButton.place(relx=0.281, rely=0.141, height=24, width=87, bordermode='ignore')
        self.scrapeButton.configure(activebackground="#400080")
        self.scrapeButton.configure(activeforeground="black")
        self.scrapeButton.configure(background="#d9d9d9")
        self.scrapeButton.configure(command=SwipeDown_support.webscrape())
        self.scrapeButton.configure(compound='left')
        self.scrapeButton.configure(disabledforeground="#a3a3a3")
        self.scrapeButton.configure(foreground="#000000")
        self.scrapeButton.configure(highlightbackground="#d9d9d9")
        self.scrapeButton.configure(highlightcolor="black")
        self.scrapeButton.configure(pady="0")
        self.scrapeButton.configure(text='''Scrape''')
        self.scrapeButton.bind('<Button-1>', lambda e: SwipeDown_support.xxx(e))
        self.Label3 = tk.Label(self.Labelframe1)
        self.Label3.place(relx=0.017, rely=0.212, height=21, width=147, bordermode='ignore')
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Sql Injection''')
        self.Button2 = tk.Button(self.Labelframe1)
        self.Button2.place(relx=0.281, rely=0.212, height=24, width=87, bordermode='ignore')
        self.Button2.configure(activebackground="beige")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=lambda: SwipeDown_support.sqlInject())
        self.Button2.configure(compound='left')
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Button''')
        self.Label4 = tk.Label(self.Labelframe1)
        self.Label4.place(relx=0.017, rely=0.306, height=11, width=147, bordermode='ignore')
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''HTTP Parameter Pollution''')
        self.Button3 = tk.Button(self.Labelframe1)
        self.Button3.place(relx=0.281, rely=0.282, height=24, width=87, bordermode='ignore')
        self.Button3.configure(activebackground="beige")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=SwipeDown_support.httpPollute())
        self.Button3.configure(compound='left')
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Button''')
        self.Label5 = tk.Label(self.Labelframe1)
        self.Label5.place(relx=0.017, rely=0.376, height=11, width=147, bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''CSS Injection''')
        self.Button4 = tk.Button(self.Labelframe1)
        self.Button4.place(relx=0.281, rely=0.353, height=24, width=87, bordermode='ignore')
        self.Button4.configure(activebackground="beige")
        self.Button4.configure(activeforeground="black")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(command=SwipeDown_support.cssInject())
        self.Button4.configure(compound='left')
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Button''')
        self.Label6 = tk.Label(self.Labelframe1)
        self.Label6.place(relx=0.017, rely=0.447, height=11, width=147, bordermode='ignore')
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Deface''')
        self.Button5 = tk.Button(self.Labelframe1)
        self.Button5.place(relx=0.281, rely=0.424, height=24, width=87, bordermode='ignore')
        self.Button5.configure(activebackground="beige")
        self.Button5.configure(activeforeground="black")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(compound='left')
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Button''')


def start_up():
    SwipeDown_support.main()


if __name__ == '__main__':
    SwipeDown_support.main()
